### ISSUE TITLE
Echoes Reverse and Echoes Twisted

### ISSUE THREAD

**Issue by cyber5** [TazTxUK/MusicModCallback#41]
The latest revision to the dark home music is not correct. They sound very similar, but the tracks that play in the Darkened Home (Echoes Twisted v2) and the Death Certificate Track (Echoes Reverse) are slightly different. Echoes Twisted v2 is the layer of Echoes of Mom (it uses layer mode 2 which replaces the track instead of playing on top of it).

I understand that this may present an issue to the Soundtrack Menu, as the vanilla XML is essentially using two track numbers to define three distinct tracks. Nat0, if you want your mod to be able to select custom tracks for all three separately (as opposed to Home being tied to Dark Home in the XML definition), I think it wouldn't be very difficult to define Echoes Twisted as its own track with its own enum that we would come up with.

Please let me know your thoughts, thanks.

**Comment by NAT0P0TAT0** [comment]
oh they are actually different? figured they were just using a layer with the same audio so that the music wouldnt be starting from the beginning when hitting the bed

i can just add a check in the soundtrack menu for dark home (rather than telling everyone to use a layer), not sure about adding a whole other track type just for death certificate, will probably just use dark closet for both
